const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

test('inventory list and overview stats use the same filter builder', () => {
  const route = fs.readFileSync(path.join(__dirname, '../src/routes/inventory.js'), 'utf8')
  const helperStart = route.indexOf('const buildInventoryFilters =')
  const listStart = route.indexOf("router.get('/list'")
  const overviewStart = route.indexOf("router.get('/stats/overview'")
  const statsStart = route.indexOf("router.get('/stats'")
  const helper = route.slice(helperStart, listStart)
  const list = route.slice(listStart, overviewStart)
  const overview = route.slice(overviewStart, statsStart)

  assert.ok(helperStart >= 0 && listStart > helperStart && overviewStart > listStart && statsStart > overviewStart)
  assert.match(list, /buildInventoryFilters\(req\.query,\s*\{\s*includeLegacyDate:\s*true\s*\}\)/)
  assert.match(list, /const effectiveStatusSql = getEffectivePhoneStatusSql\('p'\)/)
  assert.match(list, /\$\{effectiveStatusSql\} AS status/)
  assert.match(overview, /buildInventoryFilters\(req\.query\)/)
  assert.match(helper, /p\.store_id = \?/)
  assert.match(helper, /p\.inventory_operator_id = \?/)
  assert.match(helper, /isPhoneStatusAlias\(searchStr\)/)
  assert.match(helper, /if \(includeLegacyDate && date\)/)
  assert.doesNotMatch(list, /whereConditions\.push\(/)
  assert.doesNotMatch(overview, /buildInventoryStatsWhere/)
})
