const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

test('sales inventory list, export and stats share the same filter builder', () => {
  const route = fs.readFileSync(path.join(__dirname, '../src/routes/sales.js'), 'utf8')
  const listStart = route.indexOf("router.get('/phones/available'")
  const exportStart = route.indexOf("router.get('/phones/available/export'")
  const statsStart = route.indexOf("router.get('/phones/available/stats'")
  const createSaleStart = route.indexOf("router.post('/phone'")
  const customerLookupStart = route.indexOf("router.get('/customer/phone/:phone'")
  const helperStart = route.indexOf('const buildAvailablePhonesFilters =')
  const helperEnd = route.indexOf('const buildAvailablePhonesSelectQuery =')

  assert.ok(listStart >= 0 && exportStart > listStart && createSaleStart > exportStart)
  assert.ok(helperStart >= 0 && helperEnd > helperStart)

  const helper = route.slice(helperStart, helperEnd)
  const list = route.slice(listStart, exportStart)
  const exportRoute = route.slice(exportStart, createSaleStart)
  const statsRoute = route.slice(statsStart, customerLookupStart)

  assert.match(helper, /preorderDeliveryPhoneId/)
  assert.match(helper, /sale_status/)
  assert.match(helper, /brand_id/)
  assert.match(helper, /model_id/)
  assert.match(helper, /color_id/)
  assert.match(helper, /memory_id/)
  assert.match(list, /buildAvailablePhonesFilters\(req\.query,\s*\{\s*preorderDeliveryPhoneId\s*\}\)/)
  assert.match(exportRoute, /buildAvailablePhonesFilters\(req\.query\)/)
  assert.match(statsRoute, /buildAvailablePhonesFilters\(req\.query\)/)
  assert.doesNotMatch(statsRoute, /const whereConditions\s*=\s*\[COMPLETED_TRANSACTION_STATUS_SQL\]/)
  assert.doesNotMatch(list, /const whereConditions\s*=\s*\[COMPLETED_TRANSACTION_STATUS_SQL\]/)
})

test('sales available stats keep reference joins for text search filters', () => {
  const route = fs.readFileSync(path.join(__dirname, '../src/routes/sales.js'), 'utf8')
  const statsStart = route.indexOf("router.get('/phones/available/stats'")
  const statsEnd = route.indexOf("router.get('/customer/phone/:phone'")
  const stats = route.slice(statsStart, statsEnd)

  assert.ok(statsStart >= 0 && statsEnd > statsStart)
  assert.match(route, /const AVAILABLE_PHONE_REFERENCE_JOINS = `[^`]*LEFT JOIN brands b ON p\.brand_id = b\.id/)
  assert.equal((stats.match(/\$\{AVAILABLE_PHONE_REFERENCE_JOINS\}/g) || []).length, 3)
})

test('sales transaction initializes invoice sequence before beginTransaction', () => {
  const route = fs.readFileSync(path.join(__dirname, '../src/routes/sales.js'), 'utf8')
  const saleStart = route.indexOf("router.post('/phone'")
  const transactionStart = route.indexOf('await conn.beginTransaction()', saleStart)
  const beforeTransaction = route.slice(saleStart, transactionStart)

  assert.ok(saleStart >= 0 && transactionStart > saleStart)
  assert.match(beforeTransaction, /await ensureInvoiceSequenceTable\(conn\)/)
})

test('sales inventory summary and detail share base scope and resolve model within brand', () => {
  const route = fs.readFileSync(path.join(__dirname, '../src/routes/sales.js'), 'utf8')
  const helperStart = route.indexOf('const buildSalesInventoryScope =')
  const helperEnd = route.indexOf('const buildAvailablePhonesFilters =')
  const summaryStart = route.indexOf("router.get('/inventory-summary'")
  const detailStart = route.indexOf("router.get('/inventory-detail'")
  const summary = route.slice(summaryStart, detailStart)
  const detail = route.slice(detailStart)
  const scopeHelper = route.slice(helperStart, helperEnd)

  assert.ok(helperStart >= 0 && helperEnd > helperStart)
  assert.match(scopeHelper, /COMPLETED_TRANSACTION_STATUS_SQL/)
  assert.match(scopeHelper, /DATE\(p\.inventory_time\) BETWEEN \? AND \?/)
  assert.match(summary, /buildSalesInventoryScope\(\{[\s\S]*?startDate: normalizedStartDate[\s\S]*?endDate: normalizedEndDate/)
  assert.match(detail, /buildSalesInventoryScope\(\{[\s\S]*?storeId: numericStoreId[\s\S]*?supplierId: numericSupplierId/)
  assert.match(detail, /SELECT id FROM models WHERE name = \? AND brand_id = \? LIMIT 1/)
  assert.doesNotMatch(detail, /conditions\.push\('p\.is_new = \?'\)/)
})

test('sales list and summary share exact reference resolution without redundant fuzzy lookups', () => {
  const route = fs.readFileSync(path.join(__dirname, '../src/routes/sales.js'), 'utf8')
  const helperStart = route.indexOf('const SALES_REFERENCE_LOOKUP_SQL =')
  const helperEnd = route.indexOf('const buildAvailablePhonesFilters =')
  const summaryStart = route.indexOf("router.get('/inventory-summary'")
  const detailStart = route.indexOf("router.get('/inventory-detail'")
  const resolver = route.slice(helperStart, helperEnd)
  const filters = route.slice(helperEnd, summaryStart)
  const summary = route.slice(summaryStart, detailStart)
  const detail = route.slice(detailStart)

  assert.ok(helperStart >= 0 && helperEnd > helperStart)
  assert.match(resolver, /brand: 'SELECT id FROM brands WHERE LOWER\(TRIM\(name\)\) = LOWER\(\?\)'/)
  assert.match(resolver, /color: 'SELECT id FROM colors WHERE LOWER\(TRIM\(name\)\) = LOWER\(\?\)'/)
  assert.match(resolver, /memory: 'SELECT id FROM memories WHERE TRIM\(size\) = \?'/)
  for (const resource of ['brand', 'color', 'memory']) {
    assert.match(filters, new RegExp(`findSalesReferenceId\\('${resource}',`))
    assert.match(summary, new RegExp(`findSalesReferenceId\\('${resource}',`))
  }
  assert.doesNotMatch(filters, /SELECT id, name FROM colors WHERE LOWER\(name\) LIKE/)
  assert.doesNotMatch(filters, /SELECT id, size FROM memories WHERE LOWER\(size\) LIKE/)
  assert.match(detail, /SELECT id FROM models WHERE name = \? AND brand_id = \? LIMIT 1/)
  assert.match(detail, /SELECT id FROM memories WHERE size = \? LIMIT 1/)
})
