const salaryFieldMap: Record<string, string> = {
  stats_pending_salary: 'stats.pending_salary',
  stats_rest_summary: 'stats.rest_summary',
  stats_leave_summary: 'stats.leave_summary',
  stats_overtime_summary: 'stats.overtime_summary',
  template_is_default: 'template.is_default',
  template_name: 'template.name',
  template_description: 'template.description',
  template_base_salary: 'template.base_salary',
  template_commission_type: 'template.commission_type',
  template_commission_new_fixed: 'template.commission_new_fixed',
  template_commission_used_fixed: 'template.commission_used_fixed',
  template_commission_percentage: 'template.commission_percentage',
  template_overtime_hourly_rate: 'template.overtime_hourly_rate',
  template_rest_days: 'template.rest_days',
  template_auto_raise_enabled: 'template.auto_raise_enabled',
  template_auto_raise_months: 'template.auto_raise_months',
  template_auto_raise_amount: 'template.auto_raise_amount',
  template_auto_raise_max_salary: 'template.auto_raise_max_salary',
  template_is_active: 'template.is_active',
  template_employee_count: 'template.employee_count',
  employee_username: 'salary.employee_username',
  employee_name: 'salary.employee_name',
  employee_phone: 'salary.employee_phone',
  salary_template_name: 'salary.salary_template_name',
  period_start: 'salary.period_start',
  actual_work_days: 'salary.actual_work_days',
  base_salary: 'salary.base_salary',
  sales_count: 'salary.sales_count',
  commission_amount: 'salary.commission_amount',
  monthly_leave_days: 'salary.monthly_leave_days',
  leave_days: 'salary.leave_days',
  leave_deduction: 'salary.leave_deduction',
  overtime_hours: 'salary.overtime_hours',
  overtime_pay: 'salary.overtime_pay',
  net_salary: 'salary.net_salary',
  salary_status: 'salary.status',
  paid_at: 'salary.paid_at',
  payment_method: 'salary.payment_method',
  attendance_record_date: 'attendance.record_date',
  attendance_record_type: 'attendance.record_type',
  attendance_leave_type: 'attendance.leave_type',
  attendance_reason: 'attendance.reason',
  attendance_status: 'attendance.status',
  actions: 'system_info.operations'
}

export const getSalaryFieldKey = (fieldName: string) => salaryFieldMap[fieldName] || fieldName
